### ISSUE TITLE
Could you add engine property to your package.json ?

### ISSUE THREAD

**Issue by unicron** [moxystudio/node-promptly#23]
Please add the engine property to your package.json, to specify the node version compatibility.

{ "engines" : { "node" : ">=8.0" } }

Thank you!

We ran into issues with spread operator (es8+) while trying to update from 2.2.0 and targeting es6, and had to track down what happened.  Thanks!

**Comment by satazor** [comment]
If you make a MR I will accept it. Anyway, if you face a problem with a lib, always check the CHAGELOG, the breaking changes are declared there.

**Comment by nicogreenarry** [comment]
The [changelog is here](https://github.com/moxystudio/node-promptly/blob/master/CHANGELOG.md), for future reference, since I didn't see it immediately when I was looking for it myself.
