### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by mbenson** [moxystudio/node-promptly#37]
A timeout option would be helpful.

**Comment by satazor** [comment]
Agree, willing to do a PR?

**Comment by mbenson** [comment]
Most likely I didn't create one originally because my js-fu wasn't/isn't up to it. I will try to take a look in the near future and see what I can come up with. Thanks!

**Comment by loopingz** [comment]
@mbenson could you look at my pr and our conversation, I think it would be good to have another opinion on how timeout should behave with default value
